import type { DocumentSchema } from "@/lib/schema-types";

/** Papéis operacionais frequentes em campanha (lista 1–40 do briefing Amapá). */
export const CAMPAIGN_ROLE_FIELDS = [
  { key: "agenda", label: "Agenda" },
  { key: "coordenador_comboio", label: "Coordenador do comboio do governador" },
  { key: "quantifica_material_grafico", label: "Quem quantifica material gráfico" },
  { key: "autoriza_material_grafico", label: "Quem autoriza quantidade de material gráfico" },
  { key: "coordenador_plenarias", label: "Coordenador de plenárias" },
  { key: "coordenador_carreatas", label: "Coordenador de carreatas" },
  { key: "coordenador_caminhadas", label: "Coordenador de caminhadas" },
  { key: "coordenador_escritorio_central", label: "Coordenador de escritório central" },
  { key: "lista_fornecedores", label: "Lista de fornecedores da campanha" },
  { key: "coordenadores_regionais", label: "Coordenadores regionais" },
  { key: "distribui_materiais", label: "Quem distribui os materiais" },
  { key: "coordenador_times_rua", label: "Quem coordena os times de rua" },
  { key: "cobertura_midia_rua", label: "Quem faz cobertura de mídia dos eventos de rua" },
  { key: "autoriza_publicacoes_redes", label: "Quem autoriza publicações nas redes" },
  { key: "distribui_guias_tv_radio", label: "Quem distribui guias eleitorais de TV e rádio" },
  { key: "coordenador_proporcionais", label: "Quem coordena os proporcionais por partido" },
  { key: "coordenador_vereadores_prefeitos", label: "Quem coordena vereadores e prefeitos por cidade" },
  { key: "coordenador_jornalismo", label: "Quem coordena jornalismo e release" },
  { key: "coordenador_acoes_promocionais", label: "Quem coordena ações promocionais de rua" },
  { key: "coordenador_influencers", label: "Quem coordena relação com influencers e perfis" },
  { key: "coordenador_propostas", label: "Quem coordena as propostas" },
  { key: "coordenador_acoes_governo", label: "Quem coordena relação com ações de governo" },
  { key: "autoriza_pagamentos", label: "Quem autoriza os pagamentos" },
  { key: "juridico", label: "Jurídico" },
  { key: "coordenador_mobilizacao", label: "Quem coordena a mobilização" },
  { key: "coordenador_sistemas", label: "Quem coordena contratação de sistemas" },
  { key: "coordenador_pesquisas", label: "Quem coordena pesquisas e leituras" },
  { key: "coordenador_pagamentos", label: "Quem coordena os pagamentos" },
  { key: "coordenador_fundos_eleitorais", label: "Quem coordena distribuição de fundos eleitorais" },
  { key: "conselho_10_influentes", label: "Conselho das 10 pessoas mais influentes" },
  { key: "coordenador_segmentos", label: "Quem coordena os segmentos" },
  { key: "coordenador_trafego_pago", label: "Quem coordena o tráfego pago" },
  { key: "coordenador_conteudos_segmentados", label: "Quem coordena conteúdos segmentados" },
  { key: "coordenador_conselho_campanha", label: "Quem coordena o conselho da campanha" },
  { key: "coordenador_humor_viral", label: "Quem coordena humor e viral" },
  { key: "coordenador_sala_situacao", label: "Quem coordena sala de situação e leitura de dados" },
  { key: "contabilidade", label: "Contabilidade" },
  { key: "coordenador_frota", label: "Quem coordena frota e abastecimento" },
  { key: "motoristas", label: "Motoristas da campanha" },
] as const;

export function buildOnboardingAmapaSchema(): DocumentSchema {
  return {
    sections: [
      {
        key: "cliente_nucleo",
        title: "Cliente e núcleo político",
        description: "Estrutura de decisão, interlocutores e diretrizes.",
        fields: [
          { key: "estrutura_decisao", label: "Estrutura de tomada de decisão", type: "textarea", required: true },
          { key: "composicao_nucleo", label: "Composição do núcleo político", type: "textarea", required: true },
          { key: "interlocutor_coordenacao", label: "Principal interlocutor da Coordenação Geral", type: "contact", required: true },
          { key: "prioridades_7_15_30", label: "Prioridades 7 / 15 / 30 dias", type: "textarea", required: true },
          { key: "diretrizes_mensagens", label: "Diretrizes, mensagens-chave e posicionamento", type: "textarea", required: true },
          { key: "temas_sensiveis", label: "Temas sensíveis, compromissos e restrições", type: "textarea", required: false },
          { key: "rotina_candidato_reporte", label: "Rotina do candidato e formato de reporte", type: "textarea", required: false },
        ],
      },
      {
        key: "agenda_marcos",
        title: "Agenda, marcos e compromissos",
        fields: [
          { key: "agenda_confirmada", label: "Agenda confirmada do candidato", type: "textarea", required: true },
          { key: "reunioes_marcadas", label: "Reuniões políticas e institucionais marcadas", type: "list", required: false },
          { key: "eventos_mobilizacao", label: "Eventos, plenárias, caminhadas e carreatas", type: "list", required: false },
          { key: "imprensa_gravacoes", label: "Gravações, entrevistas e debates", type: "list", required: false },
          { key: "viagens", label: "Viagens e deslocamentos planejados", type: "list", required: false },
          { key: "acoes_territoriais", label: "Ações territoriais pactuadas", type: "textarea", required: false },
          { key: "prazos_calendario", label: "Datas estratégicas e prazos críticos", type: "textarea", required: true },
          { key: "demandas_pendentes_agenda", label: "Demandas de agenda aguardando decisão", type: "list", required: false },
          { key: "responsavel_agenda", label: "Responsável pela agenda e fluxo de aprovação", type: "contact", required: true },
        ],
      },
      {
        key: "equipes",
        title: "Equipes da campanha",
        fields: [
          { key: "organograma", label: "Organograma e áreas em operação", type: "textarea", required: true },
          { key: "integrantes_por_area", label: "Integrantes por área (nome, função, contato)", type: "textarea", required: true },
          { key: "responsabilidades", label: "Responsabilidades e entregas recorrentes", type: "textarea", required: false },
          { key: "autonomia_aprovacoes", label: "Lideranças, autonomia e dependências de aprovação", type: "textarea", required: false },
          { key: "canais_comunicacao", label: "Canais e grupos de comunicação", type: "list", required: false },
          { key: "rotinas_funcionando", label: "Reuniões e processos já funcionando", type: "textarea", required: false },
          { key: "gargalos_equipe", label: "Gargalos, funções descobertas e sobreposições", type: "textarea", required: false },
        ],
      },
      {
        key: "territorial",
        title: "Estrutura territorial",
        description:
          "Um registro por município, com campos padronizados. Começa com os 16 do Amapá e pode crescer.",
        fields: [
          {
            key: "municipios",
            label: "Municípios da operação",
            type: "municipio_blocks",
            required: true,
            defaultUf: "AP",
            hint: "Padrão de banco: município + responsáveis + classificação. A IA preenche por cidade.",
          },
        ],
      },
      {
        key: "fornecedores",
        title: "Fornecedores e prestadores",
        fields: [
          { key: "lista_fornecedores", label: "Fornecedores contratados e em negociação", type: "textarea", required: true },
          { key: "escopo_entregaveis", label: "Escopo, entregáveis e cronograma", type: "textarea", required: false },
          { key: "responsaveis_contrato", label: "Responsável no fornecedor e na campanha", type: "textarea", required: false },
          { key: "vigencia_pagamento", label: "Vigência, condições e fluxo de pagamento", type: "textarea", required: false },
          { key: "status_entregas", label: "Status das entregas", type: "textarea", required: false },
          { key: "pendencias_fornecedores", label: "Pendências, atrasos e decisões em aberto", type: "textarea", required: false },
        ],
      },
      {
        key: "contatos",
        title: "Contatos importantes",
        fields: [
          { key: "nucleo_pessoas_chave", label: "Núcleo político e pessoas-chave", type: "contact_list", required: true },
          { key: "parlamentares_prefeitos", label: "Parlamentares, prefeitos e vereadores relevantes", type: "contact_list", required: false },
          { key: "partidos_dirigentes", label: "Partidos e dirigentes", type: "contact_list", required: false },
          { key: "liderancas_comunitarias", label: "Lideranças comunitárias, empresariais e religiosas", type: "contact_list", required: false },
          { key: "coordenadores_municipais", label: "Coordenadores municipais e apoiadores estratégicos", type: "contact_list", required: false },
          { key: "imprensa_institucional", label: "Imprensa e relações institucionais", type: "contact_list", required: false },
        ],
      },
      {
        key: "operacao_infra",
        title: "Operação, infraestrutura e acessos",
        fields: [
          { key: "ferramentas_sistemas", label: "Ferramentas e sistemas utilizados", type: "list", required: false },
          { key: "drive_repositorio", label: "Drive/repositório oficial", type: "text", required: false },
          { key: "calendarios", label: "Calendários e agendas compartilhadas", type: "text", required: false },
          { key: "gestao_tarefas_crm", label: "Gestão de tarefas, CRM e dashboards", type: "textarea", required: false },
          { key: "grupos_whatsapp", label: "Grupos WhatsApp e canais oficiais", type: "list", required: false },
          { key: "estrutura_comites", label: "Comitês, endereços, materiais e frota", type: "textarea", required: false },
          { key: "fluxos_informacao", label: "Fluxos de informação e escalonamento", type: "textarea", required: false },
          { key: "admin_acessos", label: "Responsáveis por acessos e permissões", type: "contact", required: false },
        ],
      },
      {
        key: "inteligencia",
        title: "Informações e inteligência",
        fields: [
          { key: "pesquisas", label: "Pesquisas e estudos disponíveis", type: "textarea", required: false },
          { key: "dashboards_metricas", label: "Dashboards e métricas acompanhadas", type: "textarea", required: false },
          { key: "monitoramento", label: "Monitoramento de opinião, imprensa e redes", type: "textarea", required: false },
          { key: "mapeamentos", label: "Mapeamentos eleitorais e segmentações", type: "textarea", required: false },
          { key: "banco_realizacoes", label: "Banco de realizações, obras e entregas", type: "textarea", required: false },
          { key: "riscos_identificados", label: "Riscos políticos e operacionais já identificados", type: "list", required: false },
        ],
      },
      {
        key: "fotografia_prioridades",
        title: "Fotografia atual e prioridades imediatas",
        fields: [
          { key: "rodando_agora", label: "O que está rodando agora em cada área", type: "textarea", required: true },
          { key: "comprometido_semanas", label: "O que precisa estar pronto nas próximas semanas", type: "textarea", required: true },
          { key: "atrasado", label: "O que está atrasado", type: "list", required: false },
          { key: "travado", label: "O que está travado", type: "list", required: false },
          { key: "depende_decisao", label: "O que depende de decisão", type: "list", required: true },
          { key: "prazos_criticos", label: "Entregas com prazo crítico ou dependência", type: "textarea", required: false },
          { key: "tres_riscos_por_area", label: "Três maiores riscos por área", type: "textarea", required: false },
          { key: "tres_prioridades_por_area", label: "Três prioridades imediatas por área", type: "textarea", required: true },
        ],
      },
      {
        key: "papeis_operacionais",
        title: "Profissionais e papéis da campanha",
        description: "Nome, telefone e base por função.",
        fields: CAMPAIGN_ROLE_FIELDS.map((role) => ({
          key: role.key,
          label: role.label,
          type: "contact" as const,
          required: false,
          hint: "NOME | TELEFONE | BASE",
        })),
      },
      {
        key: "consolidacao",
        title: "Primeira consolidação da coordenação",
        fields: [
          { key: "organograma_matriz", label: "Organograma operacional e matriz de responsáveis", type: "boolean", required: false },
          { key: "mapa_territorial", label: "Mapa territorial dos 16 municípios", type: "boolean", required: false },
          { key: "base_contatos_fornecedores", label: "Base central de contatos e fornecedores", type: "boolean", required: false },
          { key: "agenda_consolidada", label: "Agenda consolidada com marcos e prazos", type: "boolean", required: false },
          { key: "painel_prioridades", label: "Painel de prioridades, pendências e decisões", type: "boolean", required: false },
          { key: "mapa_riscos", label: "Mapa de riscos, gargalos e dependências", type: "boolean", required: false },
          { key: "cronograma_integrado", label: "Cronograma integrado das principais entregas", type: "boolean", required: false },
          { key: "ritual_gestao", label: "Ritual de gestão (reuniões e reportes)", type: "boolean", required: false },
          { key: "plano_acao_imediato", label: "Plano de ação imediato para urgentes", type: "boolean", required: false },
        ],
      },
    ],
  };
}
